
:default:
  :authentication:
    :method: ClientLogin
    :email: default_email@gmail.com
    :password: default_password
    :developer_token: default_token
    :client_customer_id: 555-666-7777
    :user_agent: My Adwords API Client
  :service:
    :environment: PRODUCTION
  :library:
    :log_level: WARN
    :log_path: /tmp/adapi_production.log
#   :log_pretty_format is set to :false by default

:sandbox:
  :authentication:
    :method: ClientLogin
    :email: sandbox_email@gmail.com
    :password: sandbox_password
    :developer_token: sandbox_token
    :client_customer_id: 555-666-7777
    :user_agent: Adwords API Test
  :service:
    :environment: SANDBOX
  :library:
    :log_level: DEBUG
    :log_path: /tmp/adapi_sandbox.log
    :log_pretty_format: true
